trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: raganu-beka
  imageRepository: raganu-beka/zvani
  dockerfilePath: Dockerfile
  buildContext: .
  tag: $(Build.BuildId)

steps:
  - task: Docker@2
    displayName: Build and push image
    inputs:
      command: buildAndPush
      containerRegistry: $(dockerRegistryServiceConnection)
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      buildContext: $(buildContext)
      tags: |
        $(tag)
        $(Build.SourceBranchName)
