<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Zvani.Application</RootNamespace>
        <SpaRoot>Angular/</SpaRoot>
        <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules/**;$(SpaRoot).angular/**</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Communication.Email" Version="1.0.1"/>
        <PackageReference Include="Clerk.BackendAPI" Version="2.0.0"/>
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3"/>
        <PackageReference Include="Twilio" Version="7.14.9"/>
    </ItemGroup>

    <ItemGroup>
        <Content Remove="$(SpaRoot)**;wwwroot/**"/>
    </ItemGroup>

    <Target Name="PublishAngular" AfterTargets="ComputeFilesToPublish">
        <Exec WorkingDirectory="$(SpaRoot)" Command="bun install --frozen-lockfile"/>
        <Exec WorkingDirectory="$(SpaRoot)" Command="bun run build --configuration production"/>
        <ItemGroup>
            <AngularPublishFiles Include="wwwroot/**"/>
            <ResolvedFileToPublish Include="@(AngularPublishFiles->'%(FullPath)')">
                <RelativePath>wwwroot/%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
                <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
                <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            </ResolvedFileToPublish>
        </ItemGroup>
    </Target>

</Project>
